### ISSUE TITLE
前后端耦合怎么解决

### ISSUE THREAD

**Issue by pathfinder1989** [mozhenhau/D3Generator#1]
如题。

**Comment by mozhenhau** [comment]
抱歉，很久没有维护了。
前后端耦合？ 这个库的前提是跳转页需要传递的参数只有基础参数。
可以查看NSObject+D3里面的objectWithDict了解一下。

dict的格式如：
{
'className':"xxxxVC",
'name':'D3',
}
只有className参数是必须的， 这个字段决定了要生成的控制器ViewController
